import json

class OutputFormatter:
    """Formats and displays meeting summary and action items in a readable way."""
    
    @staticmethod
    def format_output(combine_result: str) -> None:
        try:
            data = json.loads(combine_result)
            output = data.get("final_aggregated_output", {})
            
            # Display Summary
            if "summary" in output and output["summary"]:
                print("\n" + "=" * 60)
                print("MEETING SUMMARY")
                print("=" * 60)
                print(f"\n{output['summary']}\n")
            
            # Display Action Items
            if "action_items" in output and output["action_items"]:
                print("\n" + "=" * 60)
                print("ACTION ITEMS")
                print("=" * 60)
                
                action_items = output["action_items"]
                
                # If it's a list of dicts with person and action
                if isinstance(action_items, list):
                    for item in action_items:
                        if isinstance(item, dict):
                            person = item.get("person", "Unknown")
                            action = item.get("action", "")
                            print(f"\n{person}:")
                            print(f"  • {action}")
                        else:
                            print(f"  • {item}")
                # If it's a string with person: action format
                elif isinstance(action_items, str):
                    # Parse "Person1: action1, Person2: action2" format
                    items = action_items.split(", ")
                    for item in items:
                        if ":" in item:
                            person, action = item.split(":", 1)
                            print(f"\n{person.strip()}:")
                            print(f"  • {action.strip()}")
                        else:
                            print(f"  • {item.strip()}")
                
                print()

            print("\n" + "=" * 60)
            print("DISCLAIMER: This output is generated by an AI assistant. \nPlease verify the information before taking any action.")
            print("=" * 60)
                
        except json.JSONDecodeError:
            print("\nError: Could not parse output as JSON")
            print(f"Raw output:\n{combine_result}")
        except Exception as e:
            print(f"\nError formatting output: {str(e)}")
            print(f"Raw output:\n{combine_result}")