import os
import sys
from langchain_core.messages import HumanMessage
from graph import app
import tools as tools_module

if __name__ == "__main__":
    print("\n" + "=" * 60)
    print("Meeting Summary Agent  (ReAct)")
    print("=" * 60)

    user_input = input("How can I help you today? (type 'exit' to quit): ").strip()

    if not user_input or user_input.lower() == "exit":
        sys.exit("No input provided. Exiting...")

    script_dir = os.path.dirname(os.path.abspath(__file__))
    transcript_file = os.path.join(script_dir, "transcript.txt")

    if os.path.exists(transcript_file):
        with open(transcript_file, "r", encoding="utf-8") as fh:
            transcript = fh.read().strip()
        tools_module.set_transcript(transcript)
        print("Loaded transcript.\n")
    else:
        print("Warning: transcript.txt not found.\n")

    result = app.invoke({"messages": [HumanMessage(content=user_input)]})

    final = result["messages"][-1].content
    print("\n" + "=" * 60)
    print(final)
    print("\n" + "=" * 60)
    print("DISCLAIMER: This output is generated by an AI assistant.")
    print("Please verify before taking any action.")
    print("=" * 60)
